-- HALO independent live-network domain foundation.
-- Canonical IDs are generated by the HALO application and supplied as UUIDs.
-- Provider credentials/tokens/stream secrets are never stored raw in these tables.

CREATE TABLE IF NOT EXISTS organizations (
    id UUID PRIMARY KEY,
    slug VARCHAR(80) UNIQUE NOT NULL,
    name VARCHAR(160) NOT NULL,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_members (
    id UUID PRIMARY KEY,
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(32) NOT NULL CHECK (role IN ('owner','administrator','broadcaster','moderator','editor','analyst')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, user_id, role)
);

CREATE TABLE IF NOT EXISTS channels (
    id UUID PRIMARY KEY,
    slug VARCHAR(80) UNIQUE NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    owner_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    organization_id UUID REFERENCES organizations(id) ON DELETE RESTRICT,
    status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','disabled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((owner_user_id IS NOT NULL) OR (organization_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS channel_roles (
    id UUID PRIMARY KEY,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(32) NOT NULL CHECK (role IN ('owner','administrator','broadcaster','moderator','editor','analyst')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (channel_id, user_id, role)
);

CREATE TABLE IF NOT EXISTS external_identities (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(40) NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    credential_ref TEXT,
    scopes TEXT[] NOT NULL DEFAULT '{}',
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_verified_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    UNIQUE (provider, external_user_id)
);

CREATE TABLE IF NOT EXISTS follows (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    source VARCHAR(32) NOT NULL DEFAULT 'direct',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, channel_id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
    status VARCHAR(24) NOT NULL CHECK (status IN ('pending','active','past_due','canceled','expired')),
    entitlement_id UUID,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS broadcasts (
    id UUID PRIMARY KEY,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','provisioning','live','ending','ended','failed')),
    visibility VARCHAR(24) NOT NULL DEFAULT 'public' CHECK (visibility IN ('public','unlisted','members','private')),
    scheduled_for TIMESTAMPTZ,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS broadcast_participants (
    id UUID PRIMARY KEY,
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    role VARCHAR(24) NOT NULL CHECK (role IN ('host','cohost','guest','viewer')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stream_provider_sessions (
    id UUID PRIMARY KEY,
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE RESTRICT,
    provider VARCHAR(40) NOT NULL,
    provider_session_id VARCHAR(255),
    status VARCHAR(24) NOT NULL DEFAULT 'provisioning' CHECK (status IN ('provisioning','active','ended','failed')),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, provider_session_id)
);

CREATE TABLE IF NOT EXISTS stream_keys (
    id UUID PRIMARY KEY,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    provider VARCHAR(40) NOT NULL,
    provider_key_ref TEXT NOT NULL,
    stream_key_fingerprint VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked','rotated')),
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rotated_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS external_audience_references (
    id UUID PRIMARY KEY,
    creator_channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    provider VARCHAR(40) NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    public_display_name VARCHAR(255),
    relationship_type VARCHAR(32) NOT NULL CHECK (relationship_type IN ('follower','subscriber','member','supporter')),
    relationship_since TIMESTAMPTZ,
    membership_tier VARCHAR(120),
    source_sync_time TIMESTAMPTZ NOT NULL,
    invitation_status VARCHAR(24) NOT NULL DEFAULT 'not_sent' CHECK (invitation_status IN ('not_sent','eligible','sent','claimed','suppressed')),
    claimed_halo_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (creator_channel_id, provider, external_user_id)
);

CREATE TABLE IF NOT EXISTS audience_import_jobs (
    id UUID PRIMARY KEY,
    creator_channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    provider VARCHAR(40) NOT NULL,
    requested_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(24) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','completed','failed','canceled')),
    source_cursor_ref TEXT,
    imported_count BIGINT NOT NULL DEFAULT 0 CHECK (imported_count >= 0),
    deduplicated_count BIGINT NOT NULL DEFAULT 0 CHECK (deduplicated_count >= 0),
    error_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audience_invites (
    id UUID PRIMARY KEY,
    creator_channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    audience_reference_id UUID REFERENCES external_audience_references(id) ON DELETE SET NULL,
    destination_hash VARCHAR(128),
    permission_basis VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','delivered','failed','unsubscribed','suppressed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS audience_claims (
    id UUID PRIMARY KEY,
    audience_reference_id UUID NOT NULL REFERENCES external_audience_references(id) ON DELETE RESTRICT,
    halo_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    external_identity_id UUID NOT NULL REFERENCES external_identities(id) ON DELETE RESTRICT,
    consented_follow BOOLEAN NOT NULL DEFAULT FALSE,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (audience_reference_id, halo_user_id)
);

CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY,
    slug VARCHAR(80) UNIQUE NOT NULL,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS broadcast_categories (
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    PRIMARY KEY (broadcast_id, category_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY,
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    parent_message_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
    body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
    status VARCHAR(24) NOT NULL DEFAULT 'visible' CHECK (status IN ('visible','removed','held')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS moderation_reports (
    id UUID PRIMARY KEY,
    reporter_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    channel_id UUID REFERENCES channels(id) ON DELETE RESTRICT,
    broadcast_id UUID REFERENCES broadcasts(id) ON DELETE RESTRICT,
    chat_message_id UUID REFERENCES chat_messages(id) ON DELETE RESTRICT,
    reason_code VARCHAR(64) NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved','dismissed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS moderation_actions (
    id UUID PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_scope VARCHAR(24) NOT NULL CHECK (actor_scope IN ('platform','organization','channel','automation')),
    channel_id UUID REFERENCES channels(id) ON DELETE RESTRICT,
    broadcast_id UUID REFERENCES broadcasts(id) ON DELETE RESTRICT,
    target_user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    action_type VARCHAR(32) NOT NULL CHECK (action_type IN ('mute','timeout','remove','ban','end_stream','suspend_channel','restore')),
    reason_code VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appeals (
    id UUID PRIMARY KEY,
    moderation_action_id UUID NOT NULL REFERENCES moderation_actions(id) ON DELETE RESTRICT,
    appellant_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    statement TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','upheld','overturned')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS recordings (
    id UUID PRIMARY KEY,
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE RESTRICT,
    provider VARCHAR(40) NOT NULL,
    provider_recording_id VARCHAR(255),
    object_ref TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','recording','processing','ready','failed','deleted')),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clips (
    id UUID PRIMARY KEY,
    recording_id UUID NOT NULL REFERENCES recordings(id) ON DELETE RESTRICT,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    start_ms BIGINT NOT NULL CHECK (start_ms >= 0),
    duration_ms BIGINT NOT NULL CHECK (duration_ms > 0),
    object_ref TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','processing','ready','failed','deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS action_links (
    id UUID PRIMARY KEY,
    broadcast_id UUID NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    label VARCHAR(160) NOT NULL,
    destination_url TEXT NOT NULL,
    action_type VARCHAR(40) NOT NULL CHECK (action_type IN ('source','organization','event','volunteer','donate','contact','petition','related','follow_issue')),
    position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY,
    provider VARCHAR(40) NOT NULL,
    provider_payment_id VARCHAR(255),
    idempotency_key VARCHAR(255) NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    channel_id UUID REFERENCES channels(id) ON DELETE RESTRICT,
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    currency CHAR(3) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('pending','succeeded','failed','refunded','disputed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, idempotency_key)
);

CREATE TABLE IF NOT EXISTS entitlements (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
    source_payment_id UUID REFERENCES payments(id) ON DELETE RESTRICT,
    entitlement_type VARCHAR(40) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('pending','active','revoked','expired')),
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE subscriptions
    ADD CONSTRAINT subscriptions_entitlement_fk
    FOREIGN KEY (entitlement_id) REFERENCES entitlements(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS payouts (
    id UUID PRIMARY KEY,
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
    provider VARCHAR(40) NOT NULL,
    provider_payout_id VARCHAR(255),
    amount_minor BIGINT NOT NULL CHECK (amount_minor >= 0),
    currency CHAR(3) NOT NULL,
    status VARCHAR(24) NOT NULL CHECK (status IN ('pending','processing','paid','failed','reversed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    notification_type VARCHAR(64) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS analytics_events (
    id UUID PRIMARY KEY,
    event_type VARCHAR(80) NOT NULL,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    channel_id UUID REFERENCES channels(id) ON DELETE SET NULL,
    broadcast_id UUID REFERENCES broadcasts(id) ON DELETE SET NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
    id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor_scope VARCHAR(32) NOT NULL,
    target_type VARCHAR(80),
    target_id VARCHAR(255),
    request_id VARCHAR(128),
    outcome VARCHAR(24) NOT NULL CHECK (outcome IN ('allowed','denied','succeeded','failed')),
    reason_code VARCHAR(80),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    previous_hash VARCHAR(128),
    event_hash VARCHAR(128),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_channels_owner_user_id ON channels(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_channels_organization_id ON channels(organization_id);
CREATE INDEX IF NOT EXISTS idx_broadcasts_channel_status ON broadcasts(channel_id, status);
CREATE INDEX IF NOT EXISTS idx_broadcasts_scheduled_for ON broadcasts(scheduled_for);
CREATE INDEX IF NOT EXISTS idx_provider_sessions_broadcast ON stream_provider_sessions(broadcast_id);
CREATE INDEX IF NOT EXISTS idx_audience_refs_claimed_user ON external_audience_references(claimed_halo_user_id);
CREATE INDEX IF NOT EXISTS idx_audience_import_jobs_channel ON audience_import_jobs(creator_channel_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_broadcast_created ON chat_messages(broadcast_id, created_at);
CREATE INDEX IF NOT EXISTS idx_moderation_reports_status ON moderation_reports(status, created_at);
CREATE INDEX IF NOT EXISTS idx_moderation_actions_target ON moderation_actions(target_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recordings_broadcast ON recordings(broadcast_id);
CREATE INDEX IF NOT EXISTS idx_payments_channel_status ON payments(channel_id, status);
CREATE INDEX IF NOT EXISTS idx_entitlements_user_channel ON entitlements(user_id, channel_id, status);
CREATE INDEX IF NOT EXISTS idx_audit_events_target ON audit_events(target_type, target_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON audit_events(actor_user_id, occurred_at DESC);
